Add ability to specify the scroll container node.
thcolin/react-responsive-virtual-grid pull request #1
Opened 2022-04-07 10:41 UTC by adamskoog

I ran into an issue in my application where my scroll container is not the window. I made this change so I can pass in the node of my scroll container to get things working. Seems like something that may be useful to others that may come across your project.

2022-04-07 10:56 UTC, thcolin commented
Thanks ! I'll get a look in the next days, I have an issue on an application too but didn't have time to fix it yet !

2022-04-07 11:16 UTC, thcolin requested changes
Let me know if changes are ok for you

2022-04-07 11:16 UTC, thcolin commented on src/hooks/useVirtualGrid.js
> +  const { firstRowIndex, scrolling } = useVirtualGridFirstRowIndex({ ...display, scrollContainer })
```suggestion
  const { firstRowIndex, scrolling } = useVirtualGridFirstRowIndex(display, scrollContainer)
```

2022-04-07 11:16 UTC, thcolin commented on src/hooks/useVirtualGridFirstRowIndex.js
> +const useVirtualGridFirstRowIndex = ({ layout, cell, rowOffset, scrollContainer }) => {
```suggestion
const useVirtualGridFirstRowIndex = ({ layout, cell, rowOffset }, scrollContainer) => {
```

2022-04-07 11:16 UTC, thcolin commented on src/hooks/useVirtualGridFirstRowIndex.js
> +    if (container.scrollTop) scrollTop = container.scrollTop;
```suggestion
    const scrollTop = container === window ? container.scrollY : container.scrollTop
```

2022-04-07 11:16 UTC, thcolin commented on src/hooks/useVirtualGridFirstRowIndex.js
> +  const container = scrollContainer ?? window;
```suggestion
  const container = scrollContainer ?? window
```

2022-04-07 11:17 UTC, thcolin commented on src/hooks/useVirtualGrid.js
> +  const { firstRowIndex, scrolling } = useVirtualGridFirstRowIndex({ ...display, scrollContainer })
I prefer avoid any unecessary creation of new Object in this library for performances purpose

2022-04-07 11:18 UTC, thcolin commented on src/hooks/useVirtualGridFirstRowIndex.js
> +    if (container.scrollTop) scrollTop = container.scrollTop;
Just simplify with a one line to be coherent with code below

2022-04-07 11:25 UTC, thcolin commented
👍

2022-04-07 11:25 UTC, merged

2022-04-07 11:28 UTC, adamskoog commented
Glad I could help out!

2022-04-07 23:43 UTC, adamskoog commented
I ran into a type issue with what I added. It seems like `PropTypes.node` doesn't do what I though.

I'm using useRef to get the reference to the scrollContainer, this seems to actually need `PropTypes.object` to not throw an error.

2022-04-26 16:05 UTC, thcolin commented
Published in `0.0.20`, sorry for late fix !